spring.application.name=MatchService

server.port=8087
server.servlet.context-path=/matchs

spring.data.mongodb.uri=mongodb+srv://elghalimeriem14_db_user:ubQqFHLaG5GrIML7@clustermatchmakers.ltylxsp.mongodb.net/matchsdb
spring.data.mongodb.auto-index-creation=true