spring.application.name=MatchService
spring.datasource.url=jdbc:mysql://localhost:3306/matchsdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8087
server.servlet.context-path=/matchs