spring.application.name=EventCompetitionService

server.port=8083
server.servlet.context-path=/eventsCompetitions

spring.data.mongodb.uri=mongodb+srv://elghalimeriem14_db_user:ubQqFHLaG5GrIML7@clustermatchmakers.ltylxsp.mongodb.net/eventsCompetitionsdb
spring.data.mongodb.auto-index-creation=false

services.sport-service.url=http://localhost:8084
services.match-service.url=http://localhost:8087