spring.application.name=SportService

server.port=8084
server.servlet.context-path=/sports

spring.data.mongodb.uri=mongodb+srv://elghalimeriem14_db_user:ubQqFHLaG5GrIML7@clustermatchmakers.ltylxsp.mongodb.net/sportsdb
spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.web=DEBUG

# OtherServices
services.event-competition-service.url=http://localhost:8083
services.team-service.url=http://localhost:8085
services.match-service.url=http://localhost:8087

# Upload fichiers ? taille max logo
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
