spring.application.name=SocialService
spring.datasource.url=jdbc:mysql://localhost:3306/socialdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8090
server.servlet.context-path=/social