spring.application.name=SocialService

server.port=8090
server.servlet.context-path=/social

spring.data.mongodb.uri=mongodb+srv://elghalimeriem14_db_user:ubQqFHLaG5GrIML7@clustermatchmakers.ltylxsp.mongodb.net/socialdb
spring.data.mongodb.auto-index-creation=true