spring.application.name=UserService

server.port=8081
server.servlet.context-path=/users

spring.data.mongodb.uri=mongodb+srv://elghalimeriem14_db_user:ubQqFHLaG5GrIML7@clustermatchmakers.ltylxsp.mongodb.net/usersdb
spring.data.mongodb.auto-index-creation=true