spring.application.name=UserService

server.port=8081
server.servlet.context-path=/users

spring.data.mongodb.uri=mongodb+srv://elghalimeriem14_db_user:ubQqFHLaG5GrIML7@clustermatchmakers.ltylxsp.mongodb.net/usersdb
spring.data.mongodb.auto-index-creation=true
spring.mail.username=matchmakerspi@gmail.com
spring.mail.password=ujkokmxdovufprot
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# JWT configuration
jwt.secret-key=3d9c7f4b2e1a8c6d9f0a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4
jwt.access-expiration=14400000
jwt.refresh-expiration=604800000

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.server.port=8081
management.server.base-path=/users/actuator

logging.level.org.springframework.security=TRACE