spring.application.name=ReservationService

server.port=8089
server.servlet.context-path=/reservations

spring.data.mongodb.uri=mongodb://localhost:27017/reservationsdb
spring.data.mongodb.auto-index-creation=true