spring.application.name=ReservationService

server.port=8089
server.servlet.context-path=/reservations

spring.data.mongodb.uri=mongodb+srv://elghalimeriem14_db_user:ubQqFHLaG5GrIML7@clustermatchmakers.ltylxsp.mongodb.net/reservationsdb
spring.data.mongodb.auto-index-creation=true