spring.application.name=ReservationService
server.error.include-message=always

server.port=8089
server.servlet.context-path=/reservations

spring.data.mongodb.uri=mongodb+srv://elghalimeriem14_db_user:ubQqFHLaG5GrIML7@clustermatchmakers.ltylxsp.mongodb.net/reservationsdb
spring.data.mongodb.auto-index-creation=true

# Notification Settings
# Twilio (SMS)
twilio.enabled=true
twilio.account.sid=''
twilio.auth.token=''
twilio.phone.number=+16515648130

# Meta Cloud API (WhatsApp)
meta.whatsapp.enabled=false
meta.whatsapp.token=''
meta.whatsapp.phone-id=1123986450795496