spring.application.name=RewardService

server.port=8086
server.servlet.context-path=/rewards

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/rewardsdb}
spring.data.mongodb.auto-index-creation=true
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
