spring.application.name=RewardService

server.port=8086
server.servlet.context-path=/rewards

spring.data.mongodb.uri=mongodb+srv://elghalimeriem14_db_user:ubQqFHLaG5GrIML7@clustermatchmakers.ltylxsp.mongodb.net/rewardsdb
spring.data.mongodb.auto-index-creation=true