spring.application.name=FinanceService

server.port=8091
server.servlet.context-path=/finance

spring.data.mongodb.uri=mongodb+srv://elghalimeriem14_db_user:ubQqFHLaG5GrIML7@clustermatchmakers.ltylxsp.mongodb.net/financedb
spring.data.mongodb.auto-index-creation=true