spring.application.name=ReclamationService

server.port=8082
server.servlet.context-path=/reclamations

spring.data.mongodb.uri=mongodb+srv://elghalimeriem14_db_user:ubQqFHLaG5GrIML7@clustermatchmakers.ltylxsp.mongodb.net/reclamationsdb
spring.data.mongodb.auto-index-creation=true