spring.application.name=ProductService

server.port=8092
server.servlet.context-path=/products

spring.data.mongodb.uri=mongodb+srv://elghalimeriem14_db_user:ubQqFHLaG5GrIML7@clustermatchmakers.ltylxsp.mongodb.net/productsdb
spring.data.mongodb.auto-index-creation=true

# Upload fichiers
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Dossier stockage images
app.upload-dir=uploads/products

# Stripe
stripe.currency=usd
stripe.secret.key=${STRIPE_SECRET_KEY:sk_test_placeholder}